# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoredBets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'BoredBetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoredBetsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
